get http://localhost:5000/notes

###

POST http://localhost:5000/tambahNotes
Content-Type: application/json

{
    "title": "ini tambah",
    "notes": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "is_finish": 0
}

###

PUT http://localhost:5000/edit-notes/1
Content-Type: application/json

{
    "title": "Tugas 2 Prak TCC",
    "notes": "inii tugas bentar lg dl",
    "is_finish": 0
}

###

DELETE  http://localhost:5000/delete-notes/42