get http://localhost:5000/notes

###

POST http://localhost:5000/tambahNotes
Content-Type: application/json

{
    "title": "salmaaaaaaaaaaaaaaaaaaaa",
    "notes": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "is_finish": 0
}

###

PUT http://localhost:5000/edit-notes/2
Content-Type: application/json

{
    "title": "Tugas1 Prak TCC",
    "notes": "Tugas 1 Prak TCC (Disuruh buat web app note bjirrr)",
    "is_finish": 0
}

###

DELETE  http://localhost:5000/delete-notes/1